[Fix] Fixed wrong call to registerCaptchaScript with boolean when asking configuration caused error on $ ng build
 Error: projects/ngx-captcha-lib/src/lib/components/base-recaptcha.component.ts:317:7 - error TS2559: Type 'boolean' has no properties in common with type 'RecaptchaConfiguration'.

      317       this.useGlobalDomain,
                ~~~~~~~~~~~~~~~~~~~~